### ISSUE TITLE
AJAX Request Fails with 500 Error when fetching Personal Efforts

### ISSUE THREAD

**Issue by benedict-w** [BenniG82/edge-segments#16]
Firstly love the tool, hopefully it's OK to submit an issue here, as I couldn't find anything else online.

When I try to fetch my personal efforts the page hangs with the message:

"Loading Data...
This may take some time."

![screenshot 2015-05-20 19 13 59](https://cloud.githubusercontent.com/assets/1303610/7732102/8b8dd574-ff25-11e4-83da-817b3151cc2d.png)

The AJAX request is returning a 500 error, e.g. for:
http://gniza.org/segments//rest/segmentJson/segmentPersonal?segmentId=4026210&token=ae0b8edf-580d-42f5-becd-37d0b225376d

Others are experiencing the problem here: https://forums.garmin.com/showthread.php?99688-How-to-get-Strava-Segments-on-your-Edge-1000/page19

**Comment by BenniG82** [comment]
Thanks for your bug report. I can reproduce this issue. By now I don't know what is wrong. I'll try to debug this problem ASAP.
Unfortunately I'm currently under heavy workload at my paid job so I can't improve my segment-tool :(
But fixing this bug should be possible

**Comment by BenniG82** [comment]
Please check if it works again.

**Technical Info** (for my bad memory :)) :
Strava added a new field "resource_state" to some JSON-"Entities" and I didn't allow unknown fields when deserializing from JSON to a Java Objects
`@JsonIgnoreProperties(ignoreUnknown = true)`

**Comment by benedict-w** [comment]
Thanks for looking into this. Yesterday I tried to revoke access to the app in Strava and re-authorize to see if that would solve the issue above. Unfortunately now I get an error with the authorization (so I cannot test the original issue!)

http://gniza.org/segments//rest//authorize/do?code=b88280b863b1cf33376c6d9a588812e197fcd976

**Comment by BenniG82** [comment]
Thats an other bug :( 
GH-17
But I can fix it easier.

**Comment by benedict-w** [comment]
Ah OK - that's a shame! Could you remove my athlete ID 718397?

**Comment by BenniG82** [comment]
Could you please try again?
I saw a few more errors for retrieving personal efforts in the log. Thats's strange, because in my local environment everything works fine with my latest fix.

**Comment by benedict-w** [comment]
Seems to work for me now. Many thanks!
