### ISSUE TITLE
Segment Builder unavailable

### ISSUE THREAD

**Issue by nickdyson** [BenniG82/edge-segments#18]
Hello - I used your utility a couple of times to create segment files for my Garmin Edge 520.  Disappointed to find that the application is down.  
http://gniza.org/segments/#/segment/ displays "I'm very sorry to inform you, that the Segment Builder is currently unavailable. Unfortunately Strava changed their API (the interface I use to retrieve data from Strava). Due to this change it is currently impossible to display leaderboards or to find timing-data needed to build a Segment. I hope this change was just a mistake and Strava fixes this issue. Until then I can't provide this service :(. The Segment Builder will be back again as soon as possible.

Perhaps you could get some assistance from the Veloviewer developer.  He seems to know a thing or two about the Strava API!

**Comment by nickdyson** [comment]
Veloviewer has explained why he cannot help.

**Comment by BenniG82** [comment]
Hi,
I also know some things about the strava api :)
Strava put many things to a private level only in January and broke many many apps. See for example this thread started by me:
https://groups.google.com/forum/#!topic/strava-api/SsL2ytxtZng

Currently it's only possible to retrieve your personal segment efforts and the according time-stream..

**Comment by nickdyson** [comment]
... I suppose if I had the time and the ability I could generate a FIT file for my own efforts.  I am not really interested in the full leaderboard, just improving my own performance.  Thanks

**Comment by BenniG82** [comment]
I'll take a look at it and look if its possible. 
I think it should be possible, if you don't mind building a URL by yourself e.g. something like this:
http://gniza.org/segments/generate?segmentId=1234&pr=4567890
I don't have much time currently because we are refurbishing our house and I'm a dad of two kids now, so I think changing the UI to only support personal effords is currently not possible due to a lack of time

**Comment by nickdyson** [comment]
Thanks Ben.  I would appreciate that.  I have no problems with putting the parameters in a URL.  Like you I am fairly busy at the moment, still working, but a grandparent rather than a parent.  I have experience of pre-web coding and VBA, so a retrirement ambition would be to learn how to do this for myself.

**Comment by gieljnssns** [comment]
Can one of you please tell me where to find the number after pr= ?

**Comment by BenniG82** [comment]
This was just an example URL, unfortunately I didn't have time to implement this :(
I found out, that I have to change my authorization process against Strava which makes this a bit more complicated
